### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Cally99** [luvejo/BookCRUD#11]
Pulled repo ran the commands to get running, Doesn't work. Abandonware

**Comment by larxn** [comment]
Hey, @Cally99. 

Yeah, it could be dated, to some extent. For example, NuxtJS now recommends using `fibers` instead of `node-sass`, which has been deprecated. Though it was more like a one-time thing, for learning purposes, I'm probably making a nice update this week.

Thanks for passing by.

P.D.: _Abandonware_. That's a new one for me 😁

**Comment by larxn** [comment]
Done!
